# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: mysql://homeassistant:homeassistant@core-mariadb/homeassistant?charset=utf8mb4

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.175
    - 192.168.1.103

logger:
  default: info
  logs:
    homeassistant.components.rest: debug

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

influxdb:
  host: 192.168.1.120
  port: 8086
  database: homeassistant-influx
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

homeassistant:
  allowlist_external_urls:
    - "http://192.168.1.120/config/local/garden.png"
  customize:
    sensor.develco_zhemi101_summation_delivered:
      unit_of_measurement: "kWh"

# Text to speech
tts:
  - platform: google_translate
    language: "sv"

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home-circle

#### Proximity ####
proximity:
  home:
    devices:
      - person.anton
      - person.kajsa
    tolerance: 50
    unit_of_measurement: m

# Notification group - bådas telefoner

notify:
  - platform: group
    name: "both_phones"
    services:
      - service: mobile_app_antons_pixel_7_pro
      - service: mobile_app_kajsas_s23

# Telegram
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - ###

wake_on_lan:


# Home Connect alt
home_connect_alt:
  client_id: ###
  client_secret: ###
binary_sensor:
  - platform: template
    sensors:
      person_1_in_bed:
        friendly_name: "Person 1 in Bed"
        value_template: >
          {{ states('sensor.bed')|float >= 60 }}
      person_2_in_bed:
        friendly_name: "Person 2 in Bed"
        value_template: >
          {{ states('sensor.bed')|float > 20
            and (states('sensor.bed')|float < 60 
                or states('sensor.bed')|float >= 90 )}}

# I arduino-sketchen finns ett if-statement som gör att den visar 0 om värdet är <0, ta bort detta för att testa
mqtt:
  sensor:
    - name: "Bed"
      state_topic: "home/bedroom/bed"
      unit_of_measurement: "kg"
    - name: "Bed Raw"
      state_topic: "home/bedroom/bed/raw"
      unit_of_measurement: "raw"

rest:
  resource_template: "https://sholiday.faboul.se/dagar/v2.1/{{ now().year }}/{{ now().month }}/{{ now().day }}"
  method: GET
  scan_interval: 30
  sensor:
    name: "namnsdag_raw"
    unique_id: namnsdagraw1
    json_attributes:
      - dagar

